### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by wyyaa123** [ufolr/VcpkgCleaner#1]
​Hello, today when I want to run VcpkgCleaner there are some problems. Just like that:
```
PS E:\src\VcpkgCleaner> python .\VcpkgCleaner.py   
Clean *.pdf in installed: Done!  
Clean *.pdf in packages: Done!                                                                                          
Traceback (most recent call last):                                                                                       
File "E:\src\VcpkgCleaner\VcpkgCleaner.py", line 86, in <module>                                                          
clean(vcpkg_home)                                                                                                    
File "E:\src\VcpkgCleaner\VcpkgCleaner.py", line 81, in clean                                                             clean_build_build_trees(os.path.join(home, "buildtrees"))                                                             
File "E:\src\VcpkgCleaner\VcpkgCleaner.py", line 50, in clean_build_build_trees                                           
shutil.rmtree(path_prj)                                                                                               
File "C:\Program Files\Python39\lib\shutil.py", line 748, in rmtree                                                       
return _rmtree_unsafe(path, onerror)                                                                                  
File "C:\Program Files\Python39\lib\shutil.py", line 621, in _rmtree_unsafe                                               
_rmtree_unsafe(fullname, onerror)                                                                                     
File "C:\Program Files\Python39\lib\shutil.py", line 621, in _rmtree_unsafe                                               
_rmtree_unsafe(fullname, onerror)                                                                                     
File "C:\Program Files\Python39\lib\shutil.py", line 626, in _rmtree_unsafe                                               
onerror(os.unlink, fullname, sys.exc_info())                                                                          
File "C:\Program Files\Python39\lib\shutil.py", line 624, in _rmtree_unsafe                                               
os.unlink(fullname)                                                                                                 
PermissionError: [WinError 5] 拒绝访问。: '../vcpkg\\buildtrees\\icu\\x64-windows-dbg\\config\\icu-config'
```

**Comment by ufolr** [comment]
please check does this dir(` ../vcpkg\\buildtrees\\icu\\x64-windows-dbg\\config\\icu-config`) exist.
or you can try run VcpkgCleaner AS Administrator.
